restrictedRepos:
  # You can exclude certain repos from safe-settings processing
  exclude: ['^admin$', '^repo1$', '^repo2$', '^repo3$']
  # Alternatively you can only include certain repos
  # include: ['^test$']

